version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: dockerfile.frontend
    image: frontend:latest
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - "8080:80"
