version: "3"
services:
  backend:
    container_name: backend
    build:
        context: ./
        dockerfile: dockerfile.backend
    image: backend:latest
    restart: unless-stopped
    expose:
      - 8000 
    ports:
      - "8000:8000"